# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Yertle < Formula
  desc "CLI for exploring the Yertle platform"
  homepage "https://github.com/model-context/yertle-cli"
  version "0.1.2"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/model-context/yertle-cli/releases/download/v0.1.2/yertle_darwin_amd64.tar.gz"
      sha256 "13b63535728e8d24bffe7423322d9157ab9a0e955c31434d0476600488a68ac8"

      define_method(:install) do
        bin.install "yertle"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/model-context/yertle-cli/releases/download/v0.1.2/yertle_darwin_arm64.tar.gz"
      sha256 "165ddd14f56491690aebe2c1215477ad69bab3fce6f3b70ce6f572e5b9371a0b"

      define_method(:install) do
        bin.install "yertle"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/model-context/yertle-cli/releases/download/v0.1.2/yertle_linux_amd64.tar.gz"
      sha256 "9cb4c88b196c8d6d20e591bbf858ce456babb7fe2125e8c7b0ab8783ee8032c4"
      define_method(:install) do
        bin.install "yertle"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/model-context/yertle-cli/releases/download/v0.1.2/yertle_linux_arm64.tar.gz"
      sha256 "39cfab52b1dc11976197b8b02ca5bea11f972bfebe96230b51a1215421d9ace4"
      define_method(:install) do
        bin.install "yertle"
      end
    end
  end
end
